#!/usr/bin/env python3
"""
Full pipeline script - runs complete drug-target search workflow.
Includes databases, literature, patents, and web news search.
"""

import argparse
import subprocess
import sys
import os
from pathlib import Path
from datetime import datetime


def run_script(script_name: str, args: list, scripts_dir: Path) -> bool:
    """Run a pipeline script and return success status."""
    script_path = scripts_dir / script_name
    cmd = [sys.executable, str(script_path)] + args
    print(f"\n{'='*60}")
    print(f"Running: {script_name}")
    print(f"Command: {' '.join(cmd)}")
    print('='*60)
    
    result = subprocess.run(cmd, capture_output=False)
    return result.returncode == 0


def compile_dossier(out_dir: Path, target_name: str, include_web: bool = False, include_patents: bool = False) -> None:
    """Compile final dossier from all outputs."""
    dossier_lines = [f"# Drug-Target Dossier: {target_name}\n"]
    dossier_lines.append(f"Generated: {datetime.now().isoformat()}\n")
    dossier_lines.append(f"\n---\n*This dossier was generated by nanobot's drug-target-search skill. ")
    dossier_lines.append(f"Use LLM to extract entities, reason about findings, and expand sections.*\n")
    
    # Target summary
    target_summary = out_dir / "target_summary.md"
    if target_summary.exists():
        dossier_lines.append("\n## Target Information\n")
        dossier_lines.append(target_summary.read_text())
    
    # Compounds summary
    compounds_summary = out_dir / "compounds_summary.md"
    if compounds_summary.exists():
        dossier_lines.append("\n## Compound Data\n")
        dossier_lines.append(compounds_summary.read_text())
    
    # Patent summary (if available)
    patent_summary = out_dir / "patent_summary.md"
    if patent_summary.exists():
        dossier_lines.append("\n## Patents\n")
        dossier_lines.append("*Novel compounds and IP landscape*\n\n")
        dossier_lines.append(patent_summary.read_text())
    
    # Literature summary
    lit_summary = out_dir / "literature_summary.md"
    if lit_summary.exists():
        dossier_lines.append("\n## Literature\n")
        dossier_lines.append(lit_summary.read_text())
    
    # Web news summary (if available)
    web_summary = out_dir / "web_news_summary.md"
    if web_summary.exists():
        dossier_lines.append("\n## Recent Developments (Web Search)\n")
        dossier_lines.append("*Latest news from FDA, pharma, and scientific sources*\n\n")
        dossier_lines.append(web_summary.read_text())
    
    # Structure summary
    pdb_manifest = out_dir / "pdb_manifest.tsv"
    if pdb_manifest.exists():
        import pandas as pd
        df = pd.read_csv(pdb_manifest, sep="\t")
        dossier_lines.append("\n## Structures\n")
        dossier_lines.append(f"Found {len(df)} PDB entries\n\n")
        dossier_lines.append("| PDB ID | Resolution | Method | Ligands |\n")
        dossier_lines.append("|--------|------------|--------|--------|\n")
        for _, row in df.head(10).iterrows():
            res = f"{row['resolution']:.2f}" if pd.notna(row['resolution']) else "-"
            dossier_lines.append(f"| {row['pdb_id']} | {res} | {row['method'] or '-'} | {row['ligand_ids'] or '-'} |\n")
    
    # LLM extraction hints
    dossier_lines.append("\n---\n")
    dossier_lines.append("## LLM Analysis Tasks\n")
    dossier_lines.append("\nAsk nanobot to:\n")
    dossier_lines.append("1. **Extract compounds** - List all drugs/compounds mentioned\n")
    dossier_lines.append("2. **Extract IC50 data** - Find potency values\n")
    dossier_lines.append("3. **Analyze patents** - Identify novel scaffolds and trends\n")
    dossier_lines.append("4. **Compare selectivity** - CDK4 vs CDK6, etc.\n")
    dossier_lines.append("5. **Identify companies** - Who's working on this target?\n")
    dossier_lines.append("6. **Summarize trends** - What's the direction of the field?\n")
    
    # Patent-specific LLM prompt reference
    if include_patents:
        patent_prompt = out_dir / "patent_llm_prompt.md"
        if patent_prompt.exists():
            dossier_lines.append(f"\n**Patent Analysis**: See `patent_llm_prompt.md` for detailed LLM analysis prompt.\n")
    
    (out_dir / "dossier.md").write_text("\n".join(dossier_lines))


def main() -> None:
    parser = argparse.ArgumentParser(description="Run full drug-target search pipeline")
    parser.add_argument("--target", required=True, help="Target name (e.g., CDK4)")
    parser.add_argument("--uniprot", required=True, help="UniProt accession (e.g., P11802)")
    parser.add_argument("--compounds", default="", help="Comma-separated compound names")
    parser.add_argument("--out-dir", required=True, help="Output directory")
    parser.add_argument("--max-pdb", type=int, default=50, help="Max PDB entries")
    parser.add_argument("--max-pubmed", type=int, default=10, help="Max PubMed results")
    parser.add_argument("--max-web", type=int, default=10, help="Max web search results")
    parser.add_argument("--max-patents", type=int, default=20, help="Max patent results")
    parser.add_argument("--include-web", action="store_true", help="Include web news search")
    parser.add_argument("--include-patents", action="store_true", help="Include patent search")
    parser.add_argument("--brave-api-key", help="Brave Search API key (or set BRAVE_API_KEY)")
    parser.add_argument("--lens-api-key", help="Lens.org API key for patents")
    parser.add_argument("--patent-mechanism", help="Mechanism for patent search (e.g., 'selective inhibitor')")
    parser.add_argument("--skip-target", action="store_true", help="Skip target search")
    parser.add_argument("--skip-compounds", action="store_true", help="Skip compound search")
    parser.add_argument("--skip-structures", action="store_true", help="Skip structure search")
    parser.add_argument("--skip-literature", action="store_true", help="Skip literature search")
    args = parser.parse_args()
    
    scripts_dir = Path(__file__).parent
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    
    results = {}
    
    # 1. Target search
    if not args.skip_target:
        results["target"] = run_script(
            "target_search.py",
            ["--target", args.target, "--uniprot", args.uniprot, "--out-dir", str(out_dir)],
            scripts_dir
        )
    
    # 2. Compound search
    if not args.skip_compounds and args.compounds:
        results["compounds"] = run_script(
            "compound_search.py",
            ["--names", args.compounds, "--out-dir", str(out_dir)],
            scripts_dir
        )
    
    # 3. Structure search
    if not args.skip_structures:
        results["structures"] = run_script(
            "structure_search.py",
            ["--uniprot", args.uniprot, "--out-dir", str(out_dir), "--max-results", str(args.max_pdb)],
            scripts_dir
        )
    
    # 4. Literature search
    if not args.skip_literature:
        query = f"{args.target} drug discovery"
        results["literature"] = run_script(
            "literature_search.py",
            ["--query", query, "--out-dir", str(out_dir), "--max-results", str(args.max_pubmed)],
            scripts_dir
        )
    
    # 5. Patent search (optional)
    if args.include_patents:
        patent_args = [
            "--target", args.target,
            "--out-dir", str(out_dir),
            "--count", str(args.max_patents),
            "--sort-by", "newest"
        ]
        if args.patent_mechanism:
            patent_args.extend(["--mechanism", args.patent_mechanism])
        if args.lens_api_key:
            patent_args.extend(["--lens-api-key", args.lens_api_key])
        results["patents"] = run_script("patent_search.py", patent_args, scripts_dir)
    
    # 6. Web news search (optional)
    if args.include_web:
        web_query = f"{args.target} {' '.join(args.compounds.split(',')) if args.compounds else ''} FDA approval clinical trial"
        web_args = ["--query", web_query, "--out-dir", str(out_dir), "--count", str(args.max_web)]
        if args.brave_api_key:
            web_args.extend(["--api-key", args.brave_api_key])
        results["web_news"] = run_script("web_news_search.py", web_args, scripts_dir)
    
    # 7. Compile dossier
    print("\n" + "="*60)
    print("Compiling final dossier...")
    compile_dossier(out_dir, args.target, args.include_web, args.include_patents)
    
    # Summary
    print("\n" + "="*60)
    print("PIPELINE SUMMARY")
    print("="*60)
    for step, success in results.items():
        status = "✓" if success else "✗"
        print(f"  {status} {step}")
    
    print(f"\nOutput directory: {out_dir}")
    print(f"Dossier: {out_dir / 'dossier.md'}")
    
    tips = []
    if not args.include_patents:
        tips.append("💡 Use --include-patents for novel compound discovery")
    if not args.include_web:
        tips.append("💡 Use --include-web for latest FDA/pharma news")
    
    if tips:
        print("\n" + "\n".join(tips))
    
    if "web_news" in results and not os.environ.get("BRAVE_API_KEY") and not args.brave_api_key:
        print("\n⚠️  Note: Set BRAVE_API_KEY or use --brave-api-key for web search")
    
    all_success = all(results.values())
    sys.exit(0 if all_success else 1)


if __name__ == "__main__":
    main()
